### ISSUE TITLE
Tag v0.1

### ISSUE THREAD

**Issue by NP-Hardass** [CarlEdman/godaddy-ddns#1]
Thanks for the cool script.  I'm looking forward to using it.  I was going to package it up for Gentoo, and it would be helpful if you could tag release 0.1 in git.

Thanks :)

**Comment by CarlEdman** [comment]
Thanks!  And done.

**Comment by NP-Hardass** [comment]
Terrific.  Thanks!

https://github.com/NP-Hardass/np-hardass-overlay/tree/master/net-misc/godaddy-ddns
If I come across no issues with my packaging, I'll eventually move it to the main repository for Gentoo.

Thanks again.
