### ISSUE TITLE
Handling "origin" record

### ISSUE THREAD

**Issue by NP-Hardass** [CarlEdman/godaddy-ddns#2]
The "name" field can be "@" which means the root origin, however the program currently enforces HOST.DOMAIN.TOP and interprets @ for file paths.

Unfortunately, I suspect handling it would require a pretty thorough rewrite, but I figured I'd point it out.

**Comment by dhowdy** [comment]
I just ran in to this issue as well. I'm writing a patch and will submit a pull request.

**Comment by dhowdy** [comment]
Patch submitted via pull request.  Essentially it's just substituting "%" for "@" so you can update your root DNS zone.  Like "@.domain.tld". 

Bash/sh doesn't have an issue with it, but it's possible that other shells could. I've tested this on a 16.04 system and my ASUS router running Merlin and Entware (with python3 running off of a USB drive.)  Both the command line and file updates work as expected.

**Comment by CarlEdman** [comment]
Sorry about the delay.  All fixed up now.
