### ISSUE TITLE
with Bash? 

### ISSUE THREAD

**Issue by harunresitc** [CarlEdman/godaddy-ddns#5]
How can i run this script on bash script with arguments?
And how the output from the this script is saved to a log file?

my bash:
`
#!/bin/bash

mykey="blabla"
mysecret="blabla"
domain="bla.blabla.com"

python godaddy_ddns.py --key $mykey --secret $mysecret $domain >> out.txt

sleep 15
`

When run bash:
`Traceback (most recent call last):
  File "godaddy_ddns.py", line 143, in <module>
    main()
  File "godaddy_ddns.py", line 86, in main
    with urlopen("http://ipv4.icanhazip.com/") as f: resp=f.read()
AttributeError: addinfourl instance has no attribute '__exit__'
`

and empty out.txt

**Comment by harunresitc** [comment]
bash edit:
```
publicip=`wget http://ipecho.net/plain -O - -q ; echo`
python godaddy_ddns.py --key $mykey --secret $mysecret --ip $publicip $domain > out.txt
```

```
Traceback (most recent call last):
  File "godaddy_ddns.py", line 143, in <module>
    main()
  File "godaddy_ddns.py", line 103, in main
    req = Request(url, method='PUT', data=data)
TypeError: __init__() got an unexpected keyword argument 'method'
```

**Comment by CarlEdman** [comment]
Sorry for not answering this earlier.  I believe your issue is related to running an older version of Python that does not implement the context protocol for the result of urlopen.  See this thread for potential solutions (other than upgrading to a current Python version):  https://stackoverflow.com/questions/30627937/traceback-attributeerroraddinfourl-instance-has-no-attribute-exit/30628128

**Comment by blakenorthrup** [comment]
Not a problem. I'm running the latest version on Ubuntu server 18.4.

On March 18, 2019 5:10:35 PM CDT, Carl Edman <notifications@github.com> wrote:
>Sorry for not answering this earlier.  I believe your issue is related
>to running an older version of Python that does not implement the
>context protocol for the result of urlopen.  See this thread for
>potential solutions (other than upgrading to a current Python version):
>https://stackoverflow.com/questions/30627937/traceback-attributeerroraddinfourl-instance-has-no-attribute-exit/30628128
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CarlEdman/godaddy-ddns/issues/5#issuecomment-474121073

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
